### PR TITLE
Fix apps with bad WebRTC versions

### PR DESCRIPTION
**Pull request by KohsakuOnozawa**
### Related Issues

Please list any related issues that this pull request resolves or is related to:

Notion: [link_here](https://www.notion.so/wesionary-team/WebRTC-3a21956192614ec5b1cae6cf600df9d5)

I did the same as this.
https://github.com/blackuy/react-native-twilio-video-webrtc/pull/694

### CODE REVIEW

**Review by n3rdkid — CHANGES_REQUESTED** [review]
It did resolve the bad WebRTC versions issue , but `Pre-lauch Report` reported crash.
Full log has been attached for you in the Slack thread.

Screenshot 2023-11-06 at 18 58 13

**Review by n3rdkid — APPROVED** [review]
LGTM 🚀

**Review by bibek-magar — APPROVED** [review]
LGTM 🚀

**Review by pranavo72bex — APPROVED** [review]
LGTM in normal call flow

**Pull request merged**
